#!/usr/bin/perl
####################################################################################
# Author: Saravanan Vijayakumar (brsaran@gmail.com)                                #
# Affiliation: RMRIMS, ICMR, Department of Bioinforamtics/Statistics, Patna 800007 #
# Date:	16-05-2017								   #
###################################################################################
use strict;
use Cwd qw(abs_path);
use lib abs_path().'/dependency/module/'; #setting module dependnecy path ! Do not change unless you are sure !
use brsaran::DDE; #requires DDE module developed in this study
#use Bio::Perl;
#use Bio::SeqIO;
##########################

my $path2WEKA = abs_path().'/dependency/'; #change only if weka.jar is in some other location;

#########################

#######   DO not change anyhting beyond this line, unless if you are sure ###############

###Argument Check~~~~~~~~~~~~
my ($i, $mode, $inFile, $outFile,$ou_sh,$Thresh,$MODEL);
for($i=0;$i<@ARGV;$i++){
	if($ARGV[$i] eq "-m"){
		$mode = $ARGV[$i+1];
		$mode=~s/\s//g;
		if(($mode ne 'pep')){ print "-m $mode invalid option! use 'pep' Exiting !\n"; exit;}
	}
	if($ARGV[$i] eq "-i"){
		$inFile = $ARGV[$i+1];
		$inFile=~s/\s//g;
		unless(open(INFILE,"$inFile")){die "Invalid Input file or file doesn't Exist ! Exiting";}
	}
	if($ARGV[$i] eq "-o"){
		$outFile = $ARGV[$i+1];
		$outFile=~s/\s//g;
		$ou_sh = $outFile.'_threshold';
		unless(open(OUTFILE,">$outFile")){die "Invalid Output file name or No permission to write the file ! Exiting";}
		unless(open(OUTTHRESH,">$ou_sh")){die "Invalid Output file name or No permission to write the file ! Exiting";}
		#close(OUTFILE);
	}
	if($ARGV[$i] eq "-t"){
		$Thresh = $ARGV[$i+1];
		$Thresh=~s/\s//g;
		if(($Thresh!~m/\d\.\d+/g)){ print "-t:($Thresh) should be greater than 0 and less than 1! Exiting !\n"; exit;}
	}
}
if($inFile eq ''){print "-i: cannot be null; Input file missing ! Exiting !\n"; `rm $outFile`; exit;}
if($mode eq ''){print "-m: cannot be null ! use 'pro' or 'pep' ! Exiting !\n"; `rm $outFile`; exit;}
if($outFile eq ''){print "\n-o: empty ! saving results to file LLBEP_out\n"; $outFile = "LLBEP_out";unless(open(OUTFILE,">$outFile")){die "Invalid Output file name or No permission to write the file ! Exiting";}}
if($MODEL eq ''){$MODEL = 'B';}
if($Thresh eq ''){print "-t: Threshold set to 0.6\n"; $Thresh = 0.6;}

#Argument Check Ends~~~~~~~~~~~~~~


##################### PEPTIDE MODE BEGINS #####################################
	my $Threshout;
my (@FHead,@PEP,@PRO,@Result,$Pep_DDE,$j,$line1,$line2,$temp,$Arff_header,$Pro_Out,$Pep_Out,$FinalOutPep); #Variable decclaration
$FinalOutPep = 'Sno,ID|Peptide|,Score'."\n"; #Header for CSV
$Threshout = $FinalOutPep;
$j=0; #Variable for counting the peptides

if($mode eq "pep"){ #If peptide mode is opted
	$FinalOutPep = 'Sno,ID|Peptide|,Score'."\n";
	print "\nProcessing Input...........";
	while(($line1 = <INFILE>) && ($line2 = <INFILE>)){
		$line1=~s/\s//g;		
		$FHead[$j] = $line1; #Store Header
		$line2=~s/\s//g;		
		$PEP[$j]=$line2; #Store Peptide
		#if((length($PEP[$j]))>15){print "\nInput peptide $FHead[$j] has length greater than 15. May obtain undesired result ! ";}
		if((length($PEP[$j]))<6){print "\nInput peptide $FHead[$j] has length less than 6 ! May obtain undesired result !";}
		$Pep_DDE.= DDE($line2).",P\n"; #Compute DDE
		$j++;
	}
	close (INFILE);
	$temp = './temp/'.generate_random_string(6).'.arff';
	for($i=1;$i<=400;$i++){
		$Arff_header .= "\@attribute $i numeric\n";
	}
	$Arff_header = "\@relation Epitope\n".$Arff_header.'@attribute LABEL {P,N}'."\n"."\@data\n";
	open(TEMP,">$temp");
	print TEMP $Arff_header.$Pep_DDE;
	close(TEMP);
	print "Done\n";
	$Pep_DDE=""; #Release memory	
	print "Prediction.................";
	$Pep_Out = Epi_Predict_pep($temp,$path2WEKA,$MODEL);	#Make prediction
	$Pep_Out=~s/^(?:.*\n){1,5}//; #Remove line 1-5 of weka out
	$Pep_Out=~s/(?:.*\n){1,1}\z//; #Remove last line of weka out
	`rm $temp`; #remove ARFF file
	print "Done\n";
	
	##########Result Organization################
	print "Generating Output..............";
	@Result = split("\n",$Pep_Out);

	for($j=0;$j<@Result;$j++){
		if($Result[$j]=~m/\+/g){
			$Result[$j]=substr($Result[$j],-6);
			$Result[$j]= 1-$Result[$j];
		}else{
			$Result[$j]=substr($Result[$j],-6);
		}
		$Result[$j]=~s/\s//g;
		$FinalOutPep.= ($j+1).",".$FHead[$j].'|'.$PEP[$j].'|,'. $Result[$j]."\n";
		
		if($Result[$j] >= $Thresh){$Threshout.= ($j+1).",".$FHead[$j].'|'.$PEP[$j].'|,'. $Result[$j]."\n";}

	}
	print OUTFILE $FinalOutPep;
	print OUTTHRESH $Threshout;
	close(OUTFILE);	close(OUTTHRESH);	
	print "Done\n";
}
######		PEPTIDE MODE ENDS ###########################

############################# Protein Mode Begins ##########################
$j=0; #Reinitializing $j

